In [65]:
import pandas as pd
music_data = pd.read_csv('music.csv')

#    x = music_data.drop(columns=['genre'])
#    y = music_data['genre']


#    x_train, x_test, y_train, y_test = train_test_split(x,y)


music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [64]:
from sklearn.preprocessing import LabelEncoder
codificador = LabelEncoder

music_data["genre"] = codificador.fit_transform(music_data, music_data['genre'])

from sklearn.model_selection import train_test_split

x = music_data.drop(columns=['genre'])
y = music_data['genre']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
modelo_arvore = DecisionTreeClassifier()

#    modelo_arvore.fit(x_train, y_train)

#    previsao = modelo_arvore.predict(x_test)

from sklearn.metrics import accuracy_score

#    print(accuracy_score(y_test, previsao))

import joblib

modelo_arvore = joblib.load('music-recommended.joblib')

previsao= modelo_arvore.predict(x_test)
score = accuracy_score(y_test, previsao)
score

1.0